#!/usr/bin/env python3
import subprocess
import sys
import re


FDT_FILE_RE="^U_BOOT_FDT=\"?rockchip/(?P<fdt>[\\w\\-]+)\\.dtb\"?\\s*(#.*)?\\s*$"
FDT_DIR_RE="^#?U_BOOT_FDT_DIR=\"?/usr/lib/linux-image-\"?\\s*(#.*)?\\s*$"

SHIPPED_DTBS = [
    "rk3566-quartz64-a",
    "rk3566-quartz64-b",
    "rk3566-soquartz-cm4",
    "rk3566-soquartz-blade",
    "rk3566-soquartz-model-a",
]

successful = False
dir_successful = False
lines = []

with open("/etc/default/u-boot", 'r') as f:
    for line in f:
        m = re.fullmatch(FDT_FILE_RE, line)
        if m:
            if m.group("fdt") in SHIPPED_DTBS:
                successful = True
                line = "U_BOOT_FDT=\"usr/lib/devicetrees-plebian-quartz64/rockchip/{0}.dtb\"\n".format(m.group("fdt"))
        else:
            m = re.fullmatch(FDT_DIR_RE, line)
            if m:
                dir_successful = True
                line = "U_BOOT_FDT_DIR=\"\"\n"
        lines.append(line)
if successful and dir_successful:
    with open("/etc/default/u-boot", 'w') as out_file:
        for line in lines:
            out_file.write(line)

sys.exit(subprocess.run(["u-boot-update"]).returncode)
